# Generated by Django 5.1.4 on 2025-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('fantasy', 'Fantasy'), ('sci_fi', 'Sci_Fi'), ('romance', 'Romance'), ('action', 'Action'), ('adventure', 'Adventure'), ('science', 'Science'), ('fiction', 'Fiction'), ('sport', 'Sport')], max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
